Bug_tracker/Models/CodeFirst/Ticket.cs
using Bug_tracker.Models;
using Bug_tracker.Models.CodeFirst;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bug_tracker.Models.CodeFirst
{
    public class Ticket
    {
        public Ticket()
        {
            this.TicketAttachments = new HashSet<TicketAttachment>();
            this.TicketComments = new HashSet<TicketComment>();
            this.TicketHistories = new HashSet<TicketHistory>();
        }

        // Ticket informationSS
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTimeOffset Created { get; set; }
        public DateTimeOffset? Updated { get; set; }

        // FK pointers
        public int ProjectId { get; set; }
        public int TicketTypeId { get; set; }
        public int TicketPriorityId { get; set; }
        public int TicketStatusId { get; set; }
        public string OwnerUserId { get; set; }
        public string AssignedToUserId { get; set; }

        // Navigational properites for object relationship (one to one)
        public virtual Project Project { get; set; }
        public virtual TicketStatus TicketStatus { get; set; }
        public virtual TicketPriority TicketPriority { get; set; }
        public virtual TicketType TicketType { get; set; }
        public virtual ApplicationUser OwnerUser { get; set; }
        public virtual ApplicationUser AssignedToUser { get; set; }

        // Navigational properites for object relationship (one to many)
        public virtual ICollection<TicketComment> TicketComments { get; set; }
        public virtual ICollection<TicketAttachment> TicketAttachments { get; set; }
        public virtual ICollection<TicketHistory> TicketHistories { get; set; }
    }
}

Bug_tracker/Models/CodeFirst/TicketType.cs
using Bug_tracker.Models.CodeFirst;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bug_tracker.Models.CodeFirst
{
    public class TicketType
    {
        public TicketType()
        {
            this.Tickets = new HashSet<Ticket>();

        }
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Ticket>
            Tickets { get; set; }

    }
}

Bug_tracker/Controllers/TicketAttachmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bug_tracker.Models;
using Bug_tracker.Models.CodeFirst;
using Microsoft.AspNet.Identity;
using System.IO;
using Bug_tracker.Helpers;

namespace Bug_tracker
{
    public class TicketAttachmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        //No need for a ticket attachments index

        //// GET: TicketAttachments
        //public ActionResult Index()
        //{
        //    var ticketAttachments = db.TicketAttachments.Include(t => t.Ticket).Include(t => t.User);
        //    return View(ticketAttachments.ToList());
        //}

        //// GET: TicketAttachments/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TicketAttachment ticketAttachment = db.TicketAttachments.Find(id);
        //    if (ticketAttachment == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(ticketAttachment);
        //}

        // GET: TicketAttachments/Create
        [Authorize(Roles = "Admin, Project Manager, Developer, Submitter")]
        public ActionResult Create(int? id)
        {
            UserRolesHelper rolesHelper = new UserRolesHelper(db);
            var user = db.Users.Find(User.Identity.GetUserId());
            var userRoles = rolesHelper.ListUserRoles(user.Id);
            Ticket ticket = db.Tickets.Find(id);

            ViewBag.UserId = user.Id;
            ViewBag.TicketId = id;

            if (userRoles.Contains("Admin"))
            {
                return View();
            }
            if (userRoles.Contains("Project Manager"))
            {
                if (ticket.Project.ApplicationUsers.Contains(user))
                {
                    return View();
                }

            }
            if (userRoles.Contains("Developer"))
            {
                if (ticket.AssignedToUserId == user.Id)
                {
                    return View();
                }
            }
            if (userRoles.Contains("Submitter"))
            {
                if (ticket.OwnerUserId == user.Id)
                {
                    return View();
                }
            }

           
            return View();
        }

        // POST: TicketAttachments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TicketId,UserId,Description,Created")] TicketAttachment ticketAttachment, HttpPostedFileBase fileUpload)
        {


            if (fileUpload != null && fileUpload.ContentLength > 0)
            {
                //check the file name to make sure its an image
                var ext = Path.GetExtension(fileUpload.FileName).ToLower();
                if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".bmp" && ext != ".pdf" && ext != ".doc" && ext != ".docx")
                    ModelState.AddModelError("fileUpload", "Invalid Format.");
            }


            {
                if (ModelState.IsValid)
                {
                    
                    if (fileUpload != null)
                    {
                        //relative server path
                        var filePath = "/Uploads/";
                        // path on physical drive on server
                        var absPath = Server.MapPath("~" + filePath);
                        // media url for relative path
                        ticketAttachment.FilePath = filePath + fileUpload.FileName;
                        //save image
                        fileUpload.SaveAs(Path.Combine(absPath, fileUpload.FileName));
                    }

                    ticketAttachment.UserId = User.Identity.GetUserId();
                    ticketAttachment.Created = DateTimeOffset.Now;
                    db.TicketAttachments.Add(ticketAttachment);
                    db.SaveChanges();
                    return RedirectToAction("Details", "Tickets", new { id = ticketAttachment.TicketId });
                }
            }
            //ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", ticketAttachment.TicketId);
            //ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", ticketAttachment.UserId);
            return View(ticketAttachment);
        }
    }
}
    
 
        //// GET: TicketAttachments/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TicketAttachment ticketAttachment = db.TicketAttachments.Find(id);
        //    if (ticketAttachment == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", ticketAttachment.TicketId);
        //    ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", ticketAttachment.UserId);
        //    return View(ticketAttachment);
        //}

        // POST: TicketAttachments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
//        [Authorize(Roles = "Admin")]
//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public ActionResult Edit([Bind(Include = "Id,TicketId,UserId,Description,Created,FilePath")] TicketAttachment ticketAttachment)
//        {
//            if (ModelState.IsValid)
//            {
//                db.Entry(ticketAttachment).State = EntityState.Modified;
//                db.SaveChanges();
//                return RedirectToAction("Index");
//            }
//            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", ticketAttachment.TicketId);
//            ViewBag.UserId = new SelectList(db.Users, "Id", "FirstName", ticketAttachment.UserId);
//            return View(ticketAttachment);
//        }

//        //GET: TicketAttachments/Delete/5
//        [Authorize(Roles ="Admin")]
//        public ActionResult Delete(int? id)
//        {
//            if (id == null)
//            {
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            }
//            TicketAttachment ticketAttachment = db.TicketAttachments.Find(id);
//            if (ticketAttachment == null)
//            {
//                return HttpNotFound();
//            }
//            return View(ticketAttachment);
//        }

//        // POST: TicketAttachments/Delete/5
//        [HttpPost, ActionName("Delete")]
//        [ValidateAntiForgeryToken]
//        public ActionResult DeleteConfirmed(int id)
//        {
//            TicketAttachment ticketAttachment = db.TicketAttachments.Find(id);
//            db.TicketAttachments.Remove(ticketAttachment);
//            db.SaveChanges();
//            return RedirectToAction("Index");
//        }

//        protected override void Dispose(bool disposing)
//        {
//            if (disposing)
//            {
//                db.Dispose();
//            }
//            base.Dispose(disposing);
//        }
//    }
//}

Bug_tracker/Controllers/TicketCommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bug_tracker.Models;
using Microsoft.AspNet.Identity;
using Bug_tracker.Helpers;

namespace Bug_tracker.Models.CodeFirst
{
    public class TicketCommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

       //public Ticket ticket = new Ticket();


        //// GET: TicketComments
        //public ActionResult Index()
        //{
        //    var ticketComments = db.TicketComments.Include(t => t.Ticket);
        //    return View(ticketComments.ToList());
        //}

        //// GET: TicketComments/Details/5
        //public ActionResult Details(int? id)
        //{
            
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TicketComment ticketComment = db.TicketComments.Find(id);
        //    if (ticketComment == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(ticketComment);
        //}

        // GET: TicketComments/Create
        [Authorize (Roles="Admin, Project Manager, Developer, Submitter")]
        public ActionResult Create(int? id)
        {
            ViewBag.TicketId = id;
            UserRolesHelper rolesHelper = new UserRolesHelper(db);
            var user = db.Users.Find(User.Identity.GetUserId());
            var userRoles = rolesHelper.ListUserRoles(user.Id);
            Ticket ticket = db.Tickets.Find(id);
            ViewBag.Author = user.DisplayName;

            if (userRoles.Contains("Admin"))
            {
                return View();
            }
            if (userRoles.Contains("Project Manager"))
            {
                if (ticket.Project.ApplicationUsers.Contains(user))
                {
                    return View();
                }
            }
            if (userRoles.Contains("Developer"))
            {
                if (ticket.AssignedToUserId == user.Id)
                {
                    return View();
                }
            }
            if (userRoles.Contains("Submitter"))
            {
                if (ticket.OwnerUserId == user.Id)
                {
                    return View();
                }
            }

            return RedirectToAction("Login", "Account");
        }

        //ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title");
       

        // POST: TicketComments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Project Manager, Developer, Submitter")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TicketId,UserId,Body,Created")] TicketComment ticketComment)
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            ViewBag.Author = user.DisplayName;


            if (ModelState.IsValid)
            {
                
                ticketComment.UserId = User.Identity.GetUserId();
                ticketComment.Created = DateTimeOffset.Now;
                db.TicketComments.Add(ticketComment);
                db.SaveChanges();
                return RedirectToAction("Details", "Tickets", new { id = ticketComment.TicketId });
            }

            //ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", ticketComment.TicketId);
           return RedirectToAction("Ticket");
        }

        //// GET: TicketComments/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TicketComment ticketComment = db.TicketComments.Find(id);
        //    if (ticketComment == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", ticketComment.TicketId);
        //    return View(ticketComment);
        //}

        //// POST: TicketComments/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,TicketId,UserId,Body,Created")] TicketComment ticketComment)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(ticketComment).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", ticketComment.TicketId);
        //    return View(ticketComment);
        //}

        //// GET: TicketComments/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    TicketComment ticketComment = db.TicketComments.Find(id);
        //    if (ticketComment == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(ticketComment);
        //}

        //// POST: TicketComments/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    TicketComment ticketComment = db.TicketComments.Find(id);
        //    db.TicketComments.Remove(ticketComment);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

Bug_tracker/Views/Tickets/Details.cshtml
@model Bug_tracker.Models.CodeFirst.Ticket

<<<<<<< HEAD
@{ 
    ViewBag.Author = ViewBag.Author;
}
=======
>>>>>>> refs/heads/newTemplate

<h2 class="centerText">@Model.Title</h2>
<div class="row">

    <div class="col-md-6">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Details</h3>
            </div>
            <div class="panel-body">
                <dl class="dl-horizontal">
                    <dt>
                        Assigned to
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.AssignedToUser.DisplayName)
                    </dd>
                    <dt>
                        Submitter
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.OwnerUser.DisplayName)
                    </dd>
                    <dt>
                        Project Title
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Project.Title)
                    </dd>
                    <dt>
                        Priority
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.TicketPriority.Name)
                    </dd>
                    <dt>
                        Status
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.TicketStatus.Name)
                    </dd>
                    <dt>
                        Type
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.TicketType.Name)
                    </dd>
                    <dt>
                        Ticket Title
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Title)
                    </dd>
                    <dt>
                        Description
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Description)
                    </dd>
                    <dt>
                        Created
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Created)
                    </dd>
                    <dt>
                        Updated
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Updated)
                    </dd>
                </dl>
            </div>
        </div>

    </div>


    <div class="col-md-6">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Ticket History</h3>
            </div>
            <div class="panel-body">
                @foreach (var h in Model.TicketHistories)
                {
                    if (h.Body != null)
                    {

                    <blockquote>
                        <p>@Html.Raw(h.Body)</p>
                       
                    </blockquote>
                            <br />
                    }
                }
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Comments</h3>
            </div>
            <div class="panel-body">

                <h4>Ticket Comments</h4>

                @Html.ActionLink("Leave a Comment", "Create", "TicketComments", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-primary" })


                @foreach (var c in Model.TicketComments)
                {
                    <blockquote>
                        <p>@c.Body</p>
                        <small>@c.User.DisplayName</small>
                    </blockquote>
                    <br />
                }
            </div>


        </div>
    </div>

    <div class="col-md-6">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Attachments</h3>
            </div>
            <div class="panel-body">

                <h4>Ticket Attachments</h4>
                @Html.ActionLink("Leave an Attachment", "Create", "TicketAttachments", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-primary" })
                <br />
                <div>
                    @foreach (var a in Model.TicketAttachments)
                    {
                        <blockquote>
                            <a href="@a.FilePath">@a.Description</a>  <br />
                            <small>@a.User.DisplayName</small>
                        </blockquote>
                    }
                </div>
                <br />
            </div>
        </div>
    </div>
</div>

@if (User.IsInRole("Project Manager") || User.IsInRole("Developer"))
{
    
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-primary" }) 
    
}



    @Html.ActionLink("Back to List", "Index", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-primary" })
    

Bug_tracker/Views/Tickets/Edit.cshtml
@model Bug_tracker.Models.CodeFirst.Ticket

@{
    ViewBag.Title = "Edit";
}

<<<<<<< HEAD
<h2>Edit</h2>

=======
<h2 class="centerText">Edit Ticket</h2>

<div class="progress progress-striped active">
    <div class="progress-bar progress-bar-success" style="width: 100%"></div>
</div>
>>>>>>> refs/heads/newTemplate
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
<<<<<<< HEAD
        <h4>Ticket</h4>
        <hr />
=======
      
>>>>>>> refs/heads/newTemplate
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.OwnerUserId)
        @Html.HiddenFor(model => model.Updated)
        @Html.HiddenFor(model => model.Created)


        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProjectId, "Project", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ProjectId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ProjectId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">

                <div class="form-group">
                    @Html.LabelFor(model => model.TicketTypeId, "Type", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.DropDownList("TicketTypeId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TicketTypeId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TicketPriorityId, "Priority", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.DropDownList("TicketPriorityId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.TicketPriorityId, "", new { @class = "text-danger" })
                    </div>
                </div>

                @if (User.IsInRole("Project Manager") || (User.IsInRole("Project Manager") && User.IsInRole("Developer")))
                {

                    <div class="form-group">
                        @Html.LabelFor(model => model.TicketStatusId, "Status", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.DropDownList("TicketStatusId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TicketStatusId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.AssignedToUserId, "Assigned to", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-9">
                            @Html.DropDownList("AssignedToUserId", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.AssignedToUserId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                }

                @if (User.IsInRole("Developer"))
                {
                    @Html.HiddenFor(model => model.TicketStatusId)
                    @Html.HiddenFor(model => model.AssignedToUserId)
                }

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success btn-lg" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<<<<<<< HEAD
=======
<div class="progress progress-striped active">
    <div class="progress-bar progress-bar-success" style="width: 100%"></div>
</div>
>>>>>>> refs/heads/newTemplate

@*<div class="form-group">
        @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Updated, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Updated, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Updated, "", new { @class = "text-danger" })
        </div>
    </div>*@

Bug_tracker/Views/Tickets/Index.cshtml
@model IEnumerable<Bug_tracker.Models.CodeFirst.Ticket>

@{
    ViewBag.Title = "Index";
}

<h2>Ticket Index</h2>

<div class="progress progress-striped active">
    <div class="progress-bar progress-bar-success" style="width: 100%;"></div>
</div>

@if (User.IsInRole("Submitter"))
{
    <p>
        @Html.ActionLink("Create New", "Create", null, htmlAttributes: new { @class = "btn btn-info btn-lg" })
    </p>

}


<<<<<<< HEAD
<table class="table table-bordered myTable">
=======
<table class="table table-striped table-bordered table-hover myTable">
>>>>>>> refs/heads/newTemplate
    <thead>
        <tr>

            <th>
                Owner
            </th>
            <th>
                Project Title
            </th>
            <th>
                Priority
            </th>
            <th>
                Status
            </th>
            <th>
                Ticket Type
            </th>
            <th>
                Ticket Title
            </th>

            <th>
                Created
            </th>
            <th>
                Updated
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.AssignedToUser.FirstName)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerUser.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Project.Title)
                    @* set up link on title to go to details page *@
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TicketPriority.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TicketStatus.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TicketType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Updated)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |*@
                    @Html.ActionLink("Details", "Details", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-primary" })
                    @*@Html.ActionLink("Delete", "Delete", new { id=item.Id })*@
                </td>
            </tr>
        }
    </tbody>
    
</table>


<div class="progress progress-striped active">
    <div class="progress-bar progress-bar-success" style="width: 100%;"></div>
</div>